INFO: 2021-04-27 08:38:14,762: main() 'Using profile folder /home/shivakantm/.config/variety/'
INFO: 2021-04-27 08:38:32,358: write_current_version() 'Writing current version 0.8.5 to .version'
INFO: 2021-04-27 08:38:32,358: perform_upgrade() 'Last run version was 0.8.5 or earlier, current version is 0.8.5'
INFO: 2021-04-27 08:38:32,677: process_command() 'Received command: []'
INFO: 2021-04-27 08:38:32,679: load_banned() 'Missing or invalid banned URLs list, no URLs will be banned'
WARNING: 2021-04-27 08:38:32,679: load_history() 'Could not load history file, continuing without it, no worries'
INFO: 2021-04-27 08:38:32,687: start() 'Using data_path /usr/share/variety'
INFO: 2021-04-27 08:38:32,687: load() 'Jumble loading'
INFO: 2021-04-27 08:38:32,687: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.9/site-packages/variety/plugins/builtin/__init__.py'
INFO: 2021-04-27 08:38:32,688: _walk_modules() 'Jumble loading module in APODDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/APODDownloader.py'
INFO: 2021-04-27 08:38:32,689: load() 'Jumble found plugin class: <class 'APODDownloader.APODDownloader'>: {'name': 'APODDownloader', 'description': 'NASA Astro Pic of the Day', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,689: _walk_modules() 'Jumble loading module in BingDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/BingDownloader.py'
INFO: 2021-04-27 08:38:32,689: load() 'Jumble found plugin class: <class 'BingDownloader.BingDownloader'>: {'name': 'BingDownloader', 'description': 'Bing Photo of the Day', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,690: _walk_modules() 'Jumble loading module in EarthviewDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/EarthviewDownloader.py'
INFO: 2021-04-27 08:38:32,690: load() 'Jumble found plugin class: <class 'EarthviewDownloader.EarthviewDownloader'>: {'name': 'EarthviewDownloader', 'description': 'Google Earth View Wallpapers', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,691: _walk_modules() 'Jumble loading module in MediaRSSDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/MediaRSSDownloader.py'
INFO: 2021-04-27 08:38:32,691: _walk_modules() 'Jumble loading module in MediaRSSSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/MediaRSSSource.py'
INFO: 2021-04-27 08:38:32,692: load() 'Jumble found plugin class: <class 'MediaRSSSource.MediaRSSSource'>: {'name': 'MediaRSSSource', 'description': 'Configurable source for fetching images from MediaRSS feeds', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,693: _walk_modules() 'Jumble loading module in RedditDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/RedditDownloader.py'
INFO: 2021-04-27 08:38:32,693: _walk_modules() 'Jumble loading module in RedditSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/RedditSource.py'
INFO: 2021-04-27 08:38:32,694: load() 'Jumble found plugin class: <class 'RedditSource.RedditSource'>: {'name': 'RedditSource', 'description': 'Configurable source for fetching images from Reddit', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,695: _walk_modules() 'Jumble loading module in UnsplashConfigurableSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/UnsplashConfigurableSource.py'
INFO: 2021-04-27 08:38:32,698: load() 'Jumble found plugin class: <class 'UnsplashConfigurableSource.UnsplashConfigurableSource'>: {'name': 'UnsplashConfigurableSource', 'description': 'Configurable source for fetching photos from Unsplash.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,700: _walk_modules() 'Jumble loading module in UnsplashDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/UnsplashDownloader.py'
INFO: 2021-04-27 08:38:32,701: load() 'Jumble found plugin class: <class 'UnsplashDownloader.UnsplashDownloader'>: {'name': 'UnsplashDownloader', 'description': 'High-resolution photos from Unsplash.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,702: _walk_modules() 'Jumble loading module in WallhavenDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/WallhavenDownloader.py'
INFO: 2021-04-27 08:38:32,704: _walk_modules() 'Jumble loading module in WallhavenSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/WallhavenSource.py'
INFO: 2021-04-27 08:38:32,706: load() 'Jumble found plugin class: <class 'WallhavenSource.WallhavenSource'>: {'name': 'WallhavenSource', 'description': 'Configurable source for fetching images from Wallhaven.cc', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,706: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/__init__.py'
INFO: 2021-04-27 08:38:32,706: _walk_modules() 'Jumble loading module in FortuneSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/FortuneSource.py'
INFO: 2021-04-27 08:38:32,707: load() 'Jumble found plugin class: <class 'FortuneSource.FortuneSource'>: {'name': 'UNIX fortune program', 'description': 'Displays quotes using the UNIX fortune program. You may want to install additional fortune packs, e.g. fortunes-bofh-excuses.', 'author': 'Dan Jones', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,707: _walk_modules() 'Jumble loading module in GoodreadsSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/GoodreadsSource.py'
INFO: 2021-04-27 08:38:32,715: load() 'Jumble found plugin class: <class 'GoodreadsSource.GoodreadsSource'>: {'name': 'Goodreads', 'description': 'Fetches quotes from Goodreads.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,715: _walk_modules() 'Jumble loading module in LocalFilesSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/LocalFilesSource.py'
INFO: 2021-04-27 08:38:32,716: load() 'Jumble found plugin class: <class 'LocalFilesSource.LocalFilesSource'>: {'name': 'Local text files', 'description': 'Displays quotes, defined in local text files.\nPut your own txt files in: ~/.config/variety/pluginconfig/quotes/.\nThe file format is:\n\nquote -- author\n.\nsecond quote -- another author\n.\netc...\n\nExample: http://rvelthuis.de/zips/quotes.txt', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,716: _walk_modules() 'Jumble loading module in QuotationsPageSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/QuotationsPageSource.py'
INFO: 2021-04-27 08:38:32,716: load() 'Jumble found plugin class: <class 'QuotationsPageSource.QuotationsPageSource'>: {'name': 'TheQuotationsPage.com', 'description': 'Fetches quotes from TheQuotationsPage.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,717: _walk_modules() 'Jumble loading module in UrbanDictionarySource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/UrbanDictionarySource.py'
INFO: 2021-04-27 08:38:32,717: load() 'Jumble found plugin class: <class 'UrbanDictionarySource.UrbanDictionarySource'>: {'name': 'Urban Dictionary', 'description': 'Displays definitions from Urban Dictionary', 'author': 'James Miller', 'version': '0.1'}'
INFO: 2021-04-27 08:38:32,717: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/__init__.py'
INFO: 2021-04-27 08:38:32,717: makedirs() 'Creating folder /home/shivakantm/.config/variety/pluginconfig/downloaders'
INFO: 2021-04-27 08:38:32,720: makedirs() 'Creating folder /home/shivakantm/.config/variety/Downloaded'
INFO: 2021-04-27 08:38:32,720: makedirs() 'Creating folder /home/shivakantm/.config/variety/Favorites'
INFO: 2021-04-27 08:38:32,720: makedirs() 'Creating folder /home/shivakantm/.config/variety/Fetched'
INFO: 2021-04-27 08:38:32,720: reload_config() 'Creating new downloader for type bing, location Bing Photo of the Day'
INFO: 2021-04-27 08:38:32,720: reload_config() 'Creating new downloader for type unsplash, location High-resolution photos from Unsplash.com'
INFO: 2021-04-27 08:38:32,720: reload_config() 'Creating new downloader for type apod, location NASA's Astronomy Picture of the Day'
INFO: 2021-04-27 08:38:32,720: reload_config() 'Creating new downloader for type flickr, location user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:38:32,720: reload_config() 'Creating new downloader for type earthview, location Google Earth View Wallpapers'
INFO: 2021-04-27 08:38:32,720: makedirs() 'Creating folder /home/shivakantm/.config/variety/Downloaded/Bing'
INFO: 2021-04-27 08:38:32,721: makedirs() 'Creating folder /home/shivakantm/.config/variety/Downloaded/Unsplash'
INFO: 2021-04-27 08:38:32,721: makedirs() 'Creating folder /home/shivakantm/.config/variety/Downloaded/nasa_apod'
INFO: 2021-04-27 08:38:32,721: makedirs() 'Creating folder /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_'
INFO: 2021-04-27 08:38:32,721: makedirs() 'Creating folder /home/shivakantm/.config/variety/Downloaded/Earth View'
INFO: 2021-04-27 08:38:32,721: log_options() 'Loaded options:'
INFO: 2021-04-27 08:38:32,721: log_options() 'change_enabled = True'
INFO: 2021-04-27 08:38:32,721: log_options() 'change_interval = 300'
INFO: 2021-04-27 08:38:32,721: log_options() 'change_on_start = False'
INFO: 2021-04-27 08:38:32,721: log_options() 'clipboard_enabled = False'
INFO: 2021-04-27 08:38:32,721: log_options() 'clipboard_hosts = ['wallhaven.cc', 'wallpapers.net', 'flickr.com', 'imgur.com', 'deviantart.com', 'interfacelift.com', 'vladstudio.com', 'imageshack.us', 'deviantart.net', 'imageshack.com']'
INFO: 2021-04-27 08:38:32,721: log_options() 'clipboard_use_whitelist = True'
INFO: 2021-04-27 08:38:32,721: log_options() 'clock_date_font = Ubuntu Condensed, 30'
INFO: 2021-04-27 08:38:32,721: log_options() 'clock_enabled = False'
INFO: 2021-04-27 08:38:32,722: log_options() 'clock_filter = -density 100 -font `fc-match -f '%{file[0]}' '%CLOCK_FONT_NAME'` -pointsize %CLOCK_FONT_SIZE -gravity SouthEast -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+108] '%H:%M' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+110] '%H:%M' -font `fc-match -f '%{file[0]}' '%DATE_FONT_NAME'` -pointsize %DATE_FONT_SIZE -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+58] '%A, %B %d' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+60] '%A, %B %d''
INFO: 2021-04-27 08:38:32,722: log_options() 'clock_font = Ubuntu Condensed, 70'
INFO: 2021-04-27 08:38:32,722: log_options() 'configfile = /home/shivakantm/.config/variety/variety.conf'
INFO: 2021-04-27 08:38:32,722: log_options() 'copyto_enabled = False'
INFO: 2021-04-27 08:38:32,722: log_options() 'copyto_folder = Default'
INFO: 2021-04-27 08:38:32,722: log_options() 'desired_color = [160, 160, 160]'
INFO: 2021-04-27 08:38:32,722: log_options() 'desired_color_enabled = False'
INFO: 2021-04-27 08:38:32,722: log_options() 'download_folder = /home/shivakantm/.config/variety/Downloaded'
INFO: 2021-04-27 08:38:32,722: log_options() 'download_preference_ratio = 0.9'
INFO: 2021-04-27 08:38:32,722: log_options() 'favorites_folder = /home/shivakantm/.config/variety/Favorites'
INFO: 2021-04-27 08:38:32,722: log_options() 'favorites_operations = [['Downloaded', 'Copy'], ['Fetched', 'Move'], ['Others', 'Copy']]'
INFO: 2021-04-27 08:38:32,722: log_options() 'fetched_folder = /home/shivakantm/.config/variety/Fetched'
INFO: 2021-04-27 08:38:32,722: log_options() 'filters = [[False, 'Keep original', ''], [False, 'Grayscale', '-type Grayscale'], [False, 'Heavy blur', '-blur 120x40'], [False, 'Soft blur', '-blur 20x7'], [False, 'Oil painting', '-paint 8'], [False, 'Pencil sketch', '-colorspace gray \\( +clone -tile ~/.config/variety/pencil_tile.png -draw "color 0,0 reset" +clone +swap -compose color_dodge -composite \\) -fx \'u*.2+v*.8\''], [False, 'Pointilism', '-spread 10 -noise 3'], [False, 'Pixellate', '-scale 3% -scale 3333%']]'
INFO: 2021-04-27 08:38:32,722: log_options() 'icon = Light'
INFO: 2021-04-27 08:38:32,722: log_options() 'lightness_enabled = False'
INFO: 2021-04-27 08:38:32,722: log_options() 'lightness_mode = 0'
INFO: 2021-04-27 08:38:32,722: log_options() 'min_rating = 4'
INFO: 2021-04-27 08:38:32,722: log_options() 'min_rating_enabled = False'
INFO: 2021-04-27 08:38:32,722: log_options() 'min_size = 80'
INFO: 2021-04-27 08:38:32,722: log_options() 'min_size_enabled = False'
INFO: 2021-04-27 08:38:32,722: log_options() 'quota_enabled = True'
INFO: 2021-04-27 08:38:32,722: log_options() 'quota_size = 500'
INFO: 2021-04-27 08:38:32,722: log_options() 'quotes_authors = '
INFO: 2021-04-27 08:38:32,722: log_options() 'quotes_bg_color = [80, 80, 80]'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_bg_opacity = 55'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_change_enabled = False'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_change_interval = 300'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_disabled_sources = ['QuotesDaddy']'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_enabled = False'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_favorites_file = /home/shivakantm/.config/variety/favorite_quotes.txt'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_font = Bitstream Charter 30'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_hpos = 100'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_max_length = 250'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_tags = '
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_text_color = [255, 255, 255]'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_text_shadow = False'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_vpos = 40'
INFO: 2021-04-27 08:38:32,723: log_options() 'quotes_width = 70'
INFO: 2021-04-27 08:38:32,723: log_options() 'safe_mode = False'
INFO: 2021-04-27 08:38:32,723: log_options() 'slideshow_custom_enabled = False'
INFO: 2021-04-27 08:38:32,723: log_options() 'slideshow_custom_folder = /home/shivakantm/Pictures'
INFO: 2021-04-27 08:38:32,723: log_options() 'slideshow_downloads_enabled = False'
INFO: 2021-04-27 08:38:32,723: log_options() 'slideshow_fade = 0.4'
INFO: 2021-04-27 08:38:32,723: log_options() 'slideshow_favorites_enabled = True'
INFO: 2021-04-27 08:38:32,723: log_options() 'slideshow_mode = Fullscreen'
INFO: 2021-04-27 08:38:32,723: log_options() 'slideshow_monitor = All'
INFO: 2021-04-27 08:38:32,723: log_options() 'slideshow_pan = 0.05'
INFO: 2021-04-27 08:38:32,723: log_options() 'slideshow_seconds = 6.0'
INFO: 2021-04-27 08:38:32,723: log_options() 'slideshow_sort_order = Random'
INFO: 2021-04-27 08:38:32,723: log_options() 'slideshow_sources_enabled = True'
INFO: 2021-04-27 08:38:32,723: log_options() 'slideshow_zoom = 0.2'
INFO: 2021-04-27 08:38:32,723: log_options() 'smart_enabled = False'
INFO: 2021-04-27 08:38:32,723: log_options() 'smart_notice_shown = False'
INFO: 2021-04-27 08:38:32,723: log_options() 'smart_register_shown = False'
INFO: 2021-04-27 08:38:32,723: log_options() 'sources = [[True, 'favorites', 'The Favorites folder'], [True, 'fetched', 'The Fetched folder'], [True, 'folder', '/usr/share/wallpapers'], [True, 'folder', '/usr/share/backgrounds'], [True, 'desktoppr', 'Random wallpapers from Desktoppr.co'], [True, 'bing', 'Bing Photo of the Day'], [True, 'unsplash', 'High-resolution photos from Unsplash.com'], [True, 'apod', "NASA's Astronomy Picture of the Day"], [False, 'earth', 'World Sunlight Map - live wallpaper from Die.net'], [True, 'flickr', 'user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'], [True, 'earthview', 'Google Earth View Wallpapers']]'
INFO: 2021-04-27 08:38:32,723: log_options() 'stats_enabled = True'
INFO: 2021-04-27 08:38:32,723: log_options() 'stats_notice_shown = False'
INFO: 2021-04-27 08:38:32,723: log_options() 'sync_enabled = True'
INFO: 2021-04-27 08:38:32,723: log_options() 'use_landscape_enabled = True'
INFO: 2021-04-27 08:38:32,723: reload_config() 'No need to clear prepared queue'
INFO: 2021-04-27 08:38:32,724: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/Imperial-Eagle.jpg
/usr/share/wallpapers/garuda-wallpapers/Ghosts.jpg'
INFO: 2021-04-27 08:38:32,724: load_last_change_time() 'Change interval < 6 hours, ignore persisted last_change_time, wait initially the whole interval: 300'
INFO: 2021-04-27 08:38:32,724: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/Imperial-Eagle.jpg
/usr/share/wallpapers/garuda-wallpapers/Ghosts.jpg'
INFO: 2021-04-27 08:38:32,724: regular_change_thread() 'regular_change thread running'
INFO: 2021-04-27 08:38:32,725: prepare_thread() 'Prepare thread running'
INFO: 2021-04-27 08:38:32,725: prepare_thread() 'Prepared buffer contains 0 images'
INFO: 2021-04-27 08:38:32,725: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:38:32,725: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:38:32,725: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:38:32,725: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:38:32,725: prepare_thread() 'Preparing some images'
INFO: 2021-04-27 08:38:32,725: download_one() 'Bing: Downloading an image, config: None'
INFO: 2021-04-27 08:38:32,726: download_one() 'Bing: Queue size: 0'
INFO: 2021-04-27 08:38:32,726: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:38:32,726: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:38:32,726: download_one() 'Bing: Filling queue'
INFO: 2021-04-27 08:38:32,727: update_indicator_icon() 'Creating indicator'
ERROR: 2021-04-27 08:38:32,752: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8b1e2754f0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bing.com', port=443): Max retries exceeded with url: /HPImageArchive.aspx?format=js&idx=0&n=100&mkt=en-US (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b1e2754f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/BingDownloader.py", line 61, in fill_queue
    s = Util.fetch_json(BingDownloader.BING_JSON_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bing.com', port=443): Max retries exceeded with url: /HPImageArchive.aspx?format=js&idx=0&n=100&mkt=en-US (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b1e2754f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
WARNING: 2021-04-27 08:38:32,759: create_menu() 'Variety Slideshow is not installed. This is an optional extension adding pan-and-zoom slideshows to Variety: see https://github.com/peterlevi/variety-slideshow for details'
INFO: 2021-04-27 08:38:32,760: create_indicator() 'indicator backend: AppIndicator3'
INFO: 2021-04-27 08:38:32,767: set_from_theme_icon() 'Showing indicator icon variety-indicator from GTK theme'
INFO: 2021-04-27 08:38:32,810: prepare_thread() 'After search prepared buffer contains 99 images'
INFO: 2021-04-27 08:38:32,824: do_set_wp() 'Calling do_set_wp with /usr/share/wallpapers/garuda-wallpapers/Imperial-Eagle.jpg
/usr/share/wallpapers/garuda-wallpapers/Ghosts.jpg, time: 1619492912.824893'
INFO: 2021-04-27 08:38:32,825: do_set_wp() 'Missing file or bad permissions, will not use it: /usr/share/wallpapers/garuda-wallpapers/Imperial-Eagle.jpg
/usr/share/wallpapers/garuda-wallpapers/Ghosts.jpg'
INFO: 2021-04-27 08:38:33,075: reload() 'Reloading preferences dialog'
INFO: 2021-04-27 08:38:33,758: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:38:33,759: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:38:33,759: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:38:33,759: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:38:33,759: download_one() 'Unsplash.com: Downloading an image, config: None'
INFO: 2021-04-27 08:38:33,759: download_one() 'Unsplash.com: Queue size: 0'
INFO: 2021-04-27 08:38:33,759: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:38:33,759: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:38:33,759: download_one() 'Unsplash.com: Filling queue'
INFO: 2021-04-27 08:38:33,759: fill_queue() 'Filling Unsplash queue from https://api.unsplash.com/photos/random?count=30&client_id=072e5048dfcb73a8d9ad59fcf402471518ff8df725df462b0c4fa665f466515a&orientation=landscape'
ERROR: 2021-04-27 08:38:33,761: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8b1c08d970>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.unsplash.com', port=443): Max retries exceeded with url: /photos/random?count=30&client_id=072e5048dfcb73a8d9ad59fcf402471518ff8df725df462b0c4fa665f466515a&orientation=landscape (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b1c08d970>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/UnsplashDownloader.py", line 87, in fill_queue
    r = Util.request(url)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.unsplash.com', port=443): Max retries exceeded with url: /photos/random?count=30&client_id=072e5048dfcb73a8d9ad59fcf402471518ff8df725df462b0c4fa665f466515a&orientation=landscape (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b1c08d970>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:38:34,763: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:38:34,764: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:38:34,764: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:38:34,764: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:38:34,764: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:38:34,764: download_one() 'NASA Astro Pic of the Day: Queue size: 0'
INFO: 2021-04-27 08:38:34,764: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:38:34,764: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:38:34,764: download_one() 'NASA Astro Pic of the Day: Filling queue'
INFO: 2021-04-27 08:38:34,764: fill_queue() 'Filling APOD queue from Archive'
ERROR: 2021-04-27 08:38:34,765: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8b1c08db20>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='apod.nasa.gov', port=80): Max retries exceeded with url: /apod/archivepix.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b1c08db20>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/APODDownloader.py", line 59, in fill_queue
    s = Util.html_soup(self.ROOT_URL + "archivepix.html")
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 648, in html_soup
    return bs4.BeautifulSoup(Util.fetch(url, data, **request_kwargs), "lxml")
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 636, in fetch
    return Util.request(url, data, **request_kwargs).text
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='apod.nasa.gov', port=80): Max retries exceeded with url: /apod/archivepix.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b1c08db20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:38:34,811: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-04-27 08:38:35,767: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:38:35,767: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:38:35,767: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:38:35,767: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:38:35,767: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:38:35,767: download_one() 'Flickr: Queue size: 0'
INFO: 2021-04-27 08:38:35,767: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:38:35,767: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:38:35,767: download_one() 'Flickr: Filling queue'
INFO: 2021-04-27 08:38:35,767: fetch() 'Making flickr API call: https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00'
ERROR: 2021-04-27 08:38:35,769: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8b1c08dca0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.flickr.com', port=443): Max retries exceeded with url: /services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b1c08dca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/FlickrDownloader.py", line 161, in fill_queue
    resp = FlickrDownloader.fetch(call)
  File "/usr/lib/python3.9/site-packages/variety/FlickrDownloader.py", line 74, in fetch
    return Util.fetch_json(call)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.flickr.com', port=443): Max retries exceeded with url: /services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b1c08dca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:38:36,771: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:38:36,771: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:38:36,771: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:38:36,771: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:38:36,771: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:38:36,771: download_one() 'Earth View: Queue size: 0'
INFO: 2021-04-27 08:38:36,771: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:38:36,771: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:38:36,771: download_one() 'Earth View: Filling queue'
ERROR: 2021-04-27 08:38:36,772: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8af2654070>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /limhenry/earthview/3cd868a932cd652c4373c0f6ea8618a96b08be4e/wallpaper%20changer/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8af2654070>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/EarthviewDownloader.py", line 57, in fill_queue
    queue = Util.fetch_json(DATA_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /limhenry/earthview/3cd868a932cd652c4373c0f6ea8618a96b08be4e/wallpaper%20changer/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8af2654070>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:38:49,555: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-04-27 08:38:49,655: apply() 'Applying preferences'
INFO: 2021-04-27 08:38:49,663: set_visible() 'Showing indicator icon'
INFO: 2021-04-27 08:38:49,663: set_from_theme_icon() 'Showing indicator icon variety-indicator from GTK theme'
INFO: 2021-04-27 08:38:49,664: log_options() 'Loaded options:'
INFO: 2021-04-27 08:38:49,664: log_options() 'change_enabled = True'
INFO: 2021-04-27 08:38:49,664: log_options() 'change_interval = 300'
INFO: 2021-04-27 08:38:49,664: log_options() 'change_on_start = False'
INFO: 2021-04-27 08:38:49,664: log_options() 'clipboard_enabled = False'
INFO: 2021-04-27 08:38:49,664: log_options() 'clipboard_hosts = ['wallhaven.cc', 'wallpapers.net', 'flickr.com', 'imgur.com', 'deviantart.com', 'interfacelift.com', 'vladstudio.com', 'imageshack.us', 'deviantart.net', 'imageshack.com']'
INFO: 2021-04-27 08:38:49,664: log_options() 'clipboard_use_whitelist = True'
INFO: 2021-04-27 08:38:49,664: log_options() 'clock_date_font = Ubuntu Condensed, 30'
INFO: 2021-04-27 08:38:49,664: log_options() 'clock_enabled = False'
INFO: 2021-04-27 08:38:49,664: log_options() 'clock_filter = -density 100 -font `fc-match -f '%{file[0]}' '%CLOCK_FONT_NAME'` -pointsize %CLOCK_FONT_SIZE -gravity SouthEast -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+108] '%H:%M' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+110] '%H:%M' -font `fc-match -f '%{file[0]}' '%DATE_FONT_NAME'` -pointsize %DATE_FONT_SIZE -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+58] '%A, %B %d' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+60] '%A, %B %d''
INFO: 2021-04-27 08:38:49,664: log_options() 'clock_font = Ubuntu Condensed, 70'
INFO: 2021-04-27 08:38:49,664: log_options() 'configfile = /home/shivakantm/.config/variety/variety.conf'
INFO: 2021-04-27 08:38:49,664: log_options() 'copyto_enabled = False'
INFO: 2021-04-27 08:38:49,664: log_options() 'copyto_folder = Default'
INFO: 2021-04-27 08:38:49,664: log_options() 'desired_color = [160, 160, 160]'
INFO: 2021-04-27 08:38:49,664: log_options() 'desired_color_enabled = False'
INFO: 2021-04-27 08:38:49,664: log_options() 'download_folder = /home/shivakantm/.config/variety/Downloaded'
INFO: 2021-04-27 08:38:49,665: log_options() 'download_preference_ratio = 0.9'
INFO: 2021-04-27 08:38:49,665: log_options() 'favorites_folder = /home/shivakantm/.config/variety/Favorites'
INFO: 2021-04-27 08:38:49,665: log_options() 'favorites_operations = [['Downloaded', 'Copy'], ['Fetched', 'Move'], ['Others', 'Copy']]'
INFO: 2021-04-27 08:38:49,665: log_options() 'fetched_folder = /home/shivakantm/.config/variety/Fetched'
INFO: 2021-04-27 08:38:49,665: log_options() 'filters = [[False, 'Keep original', ''], [False, 'Grayscale', '-type Grayscale'], [False, 'Heavy blur', '-blur 120x40'], [False, 'Soft blur', '-blur 20x7'], [False, 'Oil painting', '-paint 8'], [False, 'Pencil sketch', '-colorspace gray \\( +clone -tile ~/.config/variety/pencil_tile.png -draw "color 0,0 reset" +clone +swap -compose color_dodge -composite \\) -fx \'u*.2+v*.8\''], [False, 'Pointilism', '-spread 10 -noise 3'], [False, 'Pixellate', '-scale 3% -scale 3333%']]'
INFO: 2021-04-27 08:38:49,665: log_options() 'icon = Light'
INFO: 2021-04-27 08:38:49,665: log_options() 'lightness_enabled = False'
INFO: 2021-04-27 08:38:49,665: log_options() 'lightness_mode = 0'
INFO: 2021-04-27 08:38:49,665: log_options() 'min_rating = 4'
INFO: 2021-04-27 08:38:49,665: log_options() 'min_rating_enabled = False'
INFO: 2021-04-27 08:38:49,665: log_options() 'min_size = 80'
INFO: 2021-04-27 08:38:49,665: log_options() 'min_size_enabled = False'
INFO: 2021-04-27 08:38:49,665: log_options() 'quota_enabled = True'
INFO: 2021-04-27 08:38:49,665: log_options() 'quota_size = 500'
INFO: 2021-04-27 08:38:49,665: log_options() 'quotes_authors = '
INFO: 2021-04-27 08:38:49,665: log_options() 'quotes_bg_color = [80, 80, 80]'
INFO: 2021-04-27 08:38:49,665: log_options() 'quotes_bg_opacity = 55'
INFO: 2021-04-27 08:38:49,665: log_options() 'quotes_change_enabled = False'
INFO: 2021-04-27 08:38:49,665: log_options() 'quotes_change_interval = 300'
INFO: 2021-04-27 08:38:49,665: log_options() 'quotes_disabled_sources = ['']'
INFO: 2021-04-27 08:38:49,665: log_options() 'quotes_enabled = False'
INFO: 2021-04-27 08:38:49,665: log_options() 'quotes_favorites_file = /home/shivakantm/.config/variety/favorite_quotes.txt'
INFO: 2021-04-27 08:38:49,665: log_options() 'quotes_font = Bitstream Charter 30'
INFO: 2021-04-27 08:38:49,665: log_options() 'quotes_hpos = 100'
INFO: 2021-04-27 08:38:49,666: log_options() 'quotes_max_length = 250'
INFO: 2021-04-27 08:38:49,666: log_options() 'quotes_tags = '
INFO: 2021-04-27 08:38:49,666: log_options() 'quotes_text_color = [255, 255, 255]'
INFO: 2021-04-27 08:38:49,666: log_options() 'quotes_text_shadow = False'
INFO: 2021-04-27 08:38:49,666: log_options() 'quotes_vpos = 40'
INFO: 2021-04-27 08:38:49,666: log_options() 'quotes_width = 70'
INFO: 2021-04-27 08:38:49,666: log_options() 'safe_mode = False'
INFO: 2021-04-27 08:38:49,666: log_options() 'slideshow_custom_enabled = False'
INFO: 2021-04-27 08:38:49,666: log_options() 'slideshow_custom_folder = /home/shivakantm/Pictures'
INFO: 2021-04-27 08:38:49,666: log_options() 'slideshow_downloads_enabled = False'
INFO: 2021-04-27 08:38:49,666: log_options() 'slideshow_fade = 0.4'
INFO: 2021-04-27 08:38:49,666: log_options() 'slideshow_favorites_enabled = True'
INFO: 2021-04-27 08:38:49,666: log_options() 'slideshow_mode = Fullscreen'
INFO: 2021-04-27 08:38:49,666: log_options() 'slideshow_monitor = All'
INFO: 2021-04-27 08:38:49,666: log_options() 'slideshow_pan = 0.05'
INFO: 2021-04-27 08:38:49,666: log_options() 'slideshow_seconds = 6.0'
INFO: 2021-04-27 08:38:49,667: log_options() 'slideshow_sort_order = Random'
INFO: 2021-04-27 08:38:49,667: log_options() 'slideshow_sources_enabled = True'
INFO: 2021-04-27 08:38:49,667: log_options() 'slideshow_zoom = 0.2'
INFO: 2021-04-27 08:38:49,667: log_options() 'smart_enabled = False'
INFO: 2021-04-27 08:38:49,667: log_options() 'smart_notice_shown = False'
INFO: 2021-04-27 08:38:49,667: log_options() 'smart_register_shown = False'
INFO: 2021-04-27 08:38:49,667: log_options() 'sources = [[True, 'favorites', 'The Favorites folder'], [True, 'fetched', 'The Fetched folder'], [True, 'folder', '/usr/share/wallpapers'], [True, 'folder', '/usr/share/backgrounds'], [True, 'bing', 'Bing Photo of the Day'], [True, 'unsplash', 'High-resolution photos from Unsplash.com'], [True, 'apod', "NASA's Astronomy Picture of the Day"], [True, 'flickr', 'user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'], [True, 'earthview', 'Google Earth View Wallpapers'], [True, 'desktoppr', 'Random wallpapers from Desktoppr.co'], [False, 'earth', 'World Sunlight Map - live wallpaper from Die.net']]'
INFO: 2021-04-27 08:38:49,667: log_options() 'stats_enabled = True'
INFO: 2021-04-27 08:38:49,667: log_options() 'stats_notice_shown = False'
INFO: 2021-04-27 08:38:49,667: log_options() 'sync_enabled = True'
INFO: 2021-04-27 08:38:49,667: log_options() 'use_landscape_enabled = True'
INFO: 2021-04-27 08:38:49,667: clear_prepared_queue() 'Clearing prepared queue'
INFO: 2021-04-27 08:38:49,667: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/Imperial-Eagle.jpg
/usr/share/wallpapers/garuda-wallpapers/Ghosts.jpg'
INFO: 2021-04-27 08:38:49,667: prepare_thread() 'Prepared buffer contains 0 images'
INFO: 2021-04-27 08:38:49,667: prepare_thread() 'Preparing some images'
INFO: 2021-04-27 08:38:49,695: prepare_thread() 'After search prepared buffer contains 99 images'
INFO: 2021-04-27 08:38:49,695: prepare_thread() 'Prepared buffer contains 99 images'
INFO: 2021-04-27 08:38:49,770: do_set_wp() 'Calling do_set_wp with /usr/share/wallpapers/garuda-wallpapers/Imperial-Eagle.jpg
/usr/share/wallpapers/garuda-wallpapers/Ghosts.jpg, time: 1619492929.7705977'
INFO: 2021-04-27 08:38:49,771: do_set_wp() 'Missing file or bad permissions, will not use it: /usr/share/wallpapers/garuda-wallpapers/Imperial-Eagle.jpg
/usr/share/wallpapers/garuda-wallpapers/Ghosts.jpg'
INFO: 2021-04-27 08:38:51,695: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-04-27 08:38:51,695: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-04-27 08:38:52,746: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-04-27 08:38:52,747: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8af26b9100>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8af26b9100>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8af26b9100>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:39:22,777: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-04-27 08:39:22,779: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8af26b95e0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8af26b95e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8af26b95e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:39:52,808: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-04-27 08:39:52,809: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8af26b9700>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8af26b9700>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8af26b9700>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:40:22,839: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-04-27 08:40:22,841: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8af26b97c0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8af26b97c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8af26b97c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:40:52,871: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-04-27 08:40:52,872: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8b1c06aa90>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b1c06aa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b1c06aa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:41:51,696: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:41:51,696: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:41:51,696: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:41:51,696: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:41:51,696: download_one() 'Bing: Downloading an image, config: None'
INFO: 2021-04-27 08:41:51,696: download_one() 'Bing: Queue size: 0'
INFO: 2021-04-27 08:41:51,697: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:41:51,697: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:41:51,697: download_one() 'Bing: Filling queue'
ERROR: 2021-04-27 08:41:51,698: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8b1c06a850>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bing.com', port=443): Max retries exceeded with url: /HPImageArchive.aspx?format=js&idx=0&n=100&mkt=en-US (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b1c06a850>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/BingDownloader.py", line 61, in fill_queue
    s = Util.fetch_json(BingDownloader.BING_JSON_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bing.com', port=443): Max retries exceeded with url: /HPImageArchive.aspx?format=js&idx=0&n=100&mkt=en-US (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b1c06a850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:41:52,700: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:41:52,700: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:41:52,700: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:41:52,700: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:41:52,700: download_one() 'Unsplash.com: Downloading an image, config: None'
INFO: 2021-04-27 08:41:52,700: download_one() 'Unsplash.com: Queue size: 0'
INFO: 2021-04-27 08:41:52,700: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:41:52,700: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:41:52,700: download_one() 'Unsplash.com: Queue empty, but max_queue_fills_per_hour of 1 reached, will try again later'
INFO: 2021-04-27 08:41:53,702: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:41:53,702: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:41:53,702: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:41:53,702: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:41:53,702: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:41:53,702: download_one() 'NASA Astro Pic of the Day: Queue size: 0'
INFO: 2021-04-27 08:41:53,702: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:41:53,702: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:41:53,702: download_one() 'NASA Astro Pic of the Day: Filling queue'
INFO: 2021-04-27 08:41:53,702: fill_queue() 'Filling APOD queue from Archive'
ERROR: 2021-04-27 08:41:53,703: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8af26b9940>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='apod.nasa.gov', port=80): Max retries exceeded with url: /apod/archivepix.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8af26b9940>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/APODDownloader.py", line 59, in fill_queue
    s = Util.html_soup(self.ROOT_URL + "archivepix.html")
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 648, in html_soup
    return bs4.BeautifulSoup(Util.fetch(url, data, **request_kwargs), "lxml")
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 636, in fetch
    return Util.request(url, data, **request_kwargs).text
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='apod.nasa.gov', port=80): Max retries exceeded with url: /apod/archivepix.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8af26b9940>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:41:54,705: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:41:54,705: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:41:54,705: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:41:54,705: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:41:54,706: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:41:54,706: download_one() 'Flickr: Queue size: 0'
INFO: 2021-04-27 08:41:54,706: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:41:54,706: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:41:54,706: download_one() 'Flickr: Filling queue'
INFO: 2021-04-27 08:41:54,706: fetch() 'Making flickr API call: https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00'
ERROR: 2021-04-27 08:41:54,707: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8af26b9d60>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.flickr.com', port=443): Max retries exceeded with url: /services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8af26b9d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/FlickrDownloader.py", line 161, in fill_queue
    resp = FlickrDownloader.fetch(call)
  File "/usr/lib/python3.9/site-packages/variety/FlickrDownloader.py", line 74, in fetch
    return Util.fetch_json(call)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.flickr.com', port=443): Max retries exceeded with url: /services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8af26b9d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:41:55,709: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:41:55,709: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:41:55,709: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:41:55,709: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:41:55,710: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:41:55,710: download_one() 'Earth View: Queue size: 0'
INFO: 2021-04-27 08:41:55,710: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:41:55,710: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:41:55,710: download_one() 'Earth View: Filling queue'
ERROR: 2021-04-27 08:41:55,712: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8b1c08de50>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /limhenry/earthview/3cd868a932cd652c4373c0f6ea8618a96b08be4e/wallpaper%20changer/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b1c08de50>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/EarthviewDownloader.py", line 57, in fill_queue
    queue = Util.fetch_json(DATA_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /limhenry/earthview/3cd868a932cd652c4373c0f6ea8618a96b08be4e/wallpaper%20changer/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b1c08de50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:43:32,724: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2021-04-27 08:43:32,744: set_wallpaper() 'Calling set_wallpaper with /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:43:32,744: prepare_thread() 'Prepared buffer contains 98 images'
INFO: 2021-04-27 08:43:32,744: do_set_wp() 'Calling do_set_wp with /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png, time: 1619493212.7448547'
INFO: 2021-04-27 08:43:32,754: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:43:34,744: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-04-27 08:43:34,745: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:43:34,745: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:43:34,745: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:43:34,745: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:43:34,745: download_one() 'Bing: Downloading an image, config: None'
INFO: 2021-04-27 08:43:34,745: download_one() 'Bing: Queue size: 0'
INFO: 2021-04-27 08:43:34,745: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:43:34,745: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:43:34,745: download_one() 'Bing: Filling queue'
ERROR: 2021-04-27 08:43:34,749: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8b1c08db20>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bing.com', port=443): Max retries exceeded with url: /HPImageArchive.aspx?format=js&idx=0&n=100&mkt=en-US (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b1c08db20>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/BingDownloader.py", line 61, in fill_queue
    s = Util.fetch_json(BingDownloader.BING_JSON_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bing.com', port=443): Max retries exceeded with url: /HPImageArchive.aspx?format=js&idx=0&n=100&mkt=en-US (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b1c08db20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:43:35,754: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:43:35,755: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:43:35,755: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:43:35,755: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:43:35,755: download_one() 'Unsplash.com: Downloading an image, config: None'
INFO: 2021-04-27 08:43:35,755: download_one() 'Unsplash.com: Queue size: 0'
INFO: 2021-04-27 08:43:35,755: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:43:35,755: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:43:35,755: download_one() 'Unsplash.com: Queue empty, but max_queue_fills_per_hour of 1 reached, will try again later'
INFO: 2021-04-27 08:43:36,757: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:43:36,757: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:43:36,757: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:43:36,757: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:43:36,757: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:43:36,757: download_one() 'NASA Astro Pic of the Day: Queue size: 0'
INFO: 2021-04-27 08:43:36,757: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:43:36,757: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:43:36,757: download_one() 'NASA Astro Pic of the Day: Filling queue'
INFO: 2021-04-27 08:43:36,757: fill_queue() 'Filling APOD queue from Archive'
ERROR: 2021-04-27 08:43:36,758: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8af25e0e80>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='apod.nasa.gov', port=80): Max retries exceeded with url: /apod/archivepix.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8af25e0e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/APODDownloader.py", line 59, in fill_queue
    s = Util.html_soup(self.ROOT_URL + "archivepix.html")
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 648, in html_soup
    return bs4.BeautifulSoup(Util.fetch(url, data, **request_kwargs), "lxml")
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 636, in fetch
    return Util.request(url, data, **request_kwargs).text
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='apod.nasa.gov', port=80): Max retries exceeded with url: /apod/archivepix.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8af25e0e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:43:37,760: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:43:37,760: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:43:37,760: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:43:37,760: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:43:37,760: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:43:37,760: download_one() 'Flickr: Queue size: 0'
INFO: 2021-04-27 08:43:37,760: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:43:37,760: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:43:37,760: download_one() 'Flickr: Filling queue'
INFO: 2021-04-27 08:43:37,760: fetch() 'Making flickr API call: https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00'
ERROR: 2021-04-27 08:43:37,762: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8af26a54c0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.flickr.com', port=443): Max retries exceeded with url: /services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8af26a54c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/FlickrDownloader.py", line 161, in fill_queue
    resp = FlickrDownloader.fetch(call)
  File "/usr/lib/python3.9/site-packages/variety/FlickrDownloader.py", line 74, in fetch
    return Util.fetch_json(call)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.flickr.com', port=443): Max retries exceeded with url: /services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8af26a54c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:43:38,780: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:43:38,780: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:43:38,781: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:43:38,781: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:43:38,781: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:43:38,781: download_one() 'Earth View: Queue size: 0'
INFO: 2021-04-27 08:43:38,781: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:43:38,781: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:43:38,781: download_one() 'Earth View: Filling queue'
ERROR: 2021-04-27 08:43:38,783: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8af26a5280>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /limhenry/earthview/3cd868a932cd652c4373c0f6ea8618a96b08be4e/wallpaper%20changer/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8af26a5280>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1160, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.9/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/EarthviewDownloader.py", line 57, in fill_queue
    queue = Util.fetch_json(DATA_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /limhenry/earthview/3cd868a932cd652c4373c0f6ea8618a96b08be4e/wallpaper%20changer/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8af26a5280>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO: 2021-04-27 08:46:39,785: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:46:39,785: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:46:39,785: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:46:39,785: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:46:39,785: download_one() 'Bing: Downloading an image, config: None'
INFO: 2021-04-27 08:46:39,785: download_one() 'Bing: Queue size: 0'
INFO: 2021-04-27 08:46:39,785: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:46:39,785: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:46:39,785: download_one() 'Bing: Filling queue'
INFO: 2021-04-27 08:46:40,775: download_one() 'Bing: Queue populated with 7 URLs'
INFO: 2021-04-27 08:46:40,775: save_locally() 'Origin URL: https://www.bing.com/search?q=cholla+garden+joshua+tree+national+park&form=hpcapt&filters=HpDate%3a%2220210424_0700%22'
INFO: 2021-04-27 08:46:40,775: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.ChollaGarden_EN-US0706816050_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2021-04-27 08:46:40,776: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Bing/OHR.ChollaGarden_EN-US0706816050_1920x1080.jpg'
INFO: 2021-04-27 08:46:41,908: save_locally() 'Download complete'
INFO: 2021-04-27 08:46:41,908: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:46:41,910: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Bing/OHR.ChollaGarden_EN-US0706816050_1920x1080.jpg to unseen_downloads'
INFO: 2021-04-27 08:46:42,912: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:46:42,912: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:46:42,912: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:46:42,912: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:46:42,912: download_one() 'Unsplash.com: Downloading an image, config: None'
INFO: 2021-04-27 08:46:42,912: download_one() 'Unsplash.com: Queue size: 0'
INFO: 2021-04-27 08:46:42,912: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:46:42,912: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:46:42,912: download_one() 'Unsplash.com: Queue empty, but max_queue_fills_per_hour of 1 reached, will try again later'
INFO: 2021-04-27 08:46:43,913: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:46:43,913: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:46:43,913: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:46:43,913: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:46:43,913: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:46:43,913: download_one() 'NASA Astro Pic of the Day: Queue size: 0'
INFO: 2021-04-27 08:46:43,913: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:46:43,913: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:46:43,913: download_one() 'NASA Astro Pic of the Day: Filling queue'
INFO: 2021-04-27 08:46:43,913: fill_queue() 'Filling APOD queue from Archive'
INFO: 2021-04-27 08:46:48,556: download_one() 'NASA Astro Pic of the Day: Queue populated with 730 URLs'
INFO: 2021-04-27 08:46:48,556: download_queue_item() 'APOD URL: http://apod.nasa.gov/apod/ap200217.html'
INFO: 2021-04-27 08:46:51,221: download_queue_item() 'Image URL: http://apod.nasa.gov/apod/image/2002/Betelgeuse2019_ESO_1280.jpg'
INFO: 2021-04-27 08:46:51,221: save_locally() 'Origin URL: http://apod.nasa.gov/apod/ap200217.html'
INFO: 2021-04-27 08:46:51,221: save_locally() 'Image URL: http://apod.nasa.gov/apod/image/2002/Betelgeuse2019_ESO_1280.jpg'
INFO: 2021-04-27 08:46:51,221: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/nasa_apod/Betelgeuse2019_ESO_1280.jpg'
INFO: 2021-04-27 08:46:55,001: save_locally() 'Download complete'
INFO: 2021-04-27 08:46:55,002: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:46:55,003: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:46:55,003: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/nasa_apod/Betelgeuse2019_ESO_1280.jpg to unseen_downloads'
INFO: 2021-04-27 08:46:56,004: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:46:56,004: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:46:56,005: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:46:56,005: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:46:56,005: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:46:56,005: download_one() 'Flickr: Queue size: 0'
INFO: 2021-04-27 08:46:56,005: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:46:56,005: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:46:56,005: download_one() 'Flickr: Filling queue'
INFO: 2021-04-27 08:46:56,005: fetch() 'Making flickr API call: https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00'
INFO: 2021-04-27 08:46:56,864: fill_queue() '1 pages in the search results, using page 1'
INFO: 2021-04-27 08:46:56,864: fetch() 'Making flickr API call: https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=0553a848c09bcfd21d3a984d9408c04e&per_page=500&tag_mode=all&format=json&nojsoncallback=1&user_id=93647178@N00&extras=owner_name,description,tags,o_dims,url_o,url_k,url_h,url_l&page=1'
INFO: 2021-04-27 08:46:57,729: process_photos_in_response() 'Queue size is 0, populating with images for size suffix o'
INFO: 2021-04-27 08:46:57,733: download_one() 'Flickr: Queue populated with 81 URLs'
INFO: 2021-04-27 08:46:57,733: save_locally() 'Origin URL: https://www.flickr.com/photos/93647178@N00/7527795376'
INFO: 2021-04-27 08:46:57,733: save_locally() 'Image URL: https://live.staticflickr.com/8145/7527795376_10cf9345d9_o.jpg'
INFO: 2021-04-27 08:46:57,733: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527795376_10cf9345d9_o.jpg'
INFO: 2021-04-27 08:46:59,170: save_locally() 'Download complete'
INFO: 2021-04-27 08:46:59,170: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:46:59,171: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:46:59,172: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527795376_10cf9345d9_o.jpg to unseen_downloads'
INFO: 2021-04-27 08:47:00,173: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:47:00,174: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:47:00,174: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:47:00,174: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:47:00,174: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:47:00,174: download_one() 'Earth View: Queue size: 0'
INFO: 2021-04-27 08:47:00,174: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:47:00,174: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:47:00,174: download_one() 'Earth View: Filling queue'
INFO: 2021-04-27 08:47:01,821: download_one() 'Earth View: Queue populated with 1511 URLs'
INFO: 2021-04-27 08:47:01,821: save_locally() 'Origin URL: https://earthview.withgoogle.com/5583'
INFO: 2021-04-27 08:47:01,821: save_locally() 'Image URL: https://www.gstatic.com/prettyearth/assets/full/5583.jpg'
INFO: 2021-04-27 08:47:01,821: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Earth View/Gobabeb, Namibia (ID-5583).jpg'
INFO: 2021-04-27 08:47:02,625: save_locally() 'Download complete'
INFO: 2021-04-27 08:47:02,625: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:47:02,626: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:47:02,627: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Earth View/Gobabeb, Namibia (ID-5583).jpg to unseen_downloads'
INFO: 2021-04-27 08:47:03,628: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:47:03,628: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:47:03,628: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:47:03,628: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:47:03,628: download_one() 'Bing: Downloading an image, config: None'
INFO: 2021-04-27 08:47:03,628: download_one() 'Bing: Queue size: 6'
INFO: 2021-04-27 08:47:03,628: download_one() 'Bing: Queue populated with 6 URLs'
INFO: 2021-04-27 08:47:03,629: save_locally() 'Origin URL: https://www.bing.com/search?q=madeira+island&form=hpcapt&filters=HpDate%3a%2220210421_0700%22'
INFO: 2021-04-27 08:47:03,629: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.SaoJorgeMadeira_EN-US8002002726_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2021-04-27 08:47:03,629: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Bing/OHR.SaoJorgeMadeira_EN-US8002002726_1920x1080.jpg'
INFO: 2021-04-27 08:47:04,509: save_locally() 'Download complete'
INFO: 2021-04-27 08:47:04,509: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:47:04,510: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:47:04,510: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Bing/OHR.SaoJorgeMadeira_EN-US8002002726_1920x1080.jpg to unseen_downloads'
INFO: 2021-04-27 08:47:05,512: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:47:05,512: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:47:05,512: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:47:05,512: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:47:05,512: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:47:05,512: download_one() 'NASA Astro Pic of the Day: Queue size: 729'
INFO: 2021-04-27 08:47:05,512: download_one() 'NASA Astro Pic of the Day: Queue populated with 729 URLs'
INFO: 2021-04-27 08:47:05,512: download_queue_item() 'APOD URL: http://apod.nasa.gov/apod/ap200316.html'
INFO: 2021-04-27 08:47:08,051: download_queue_item() 'Image URL: http://apod.nasa.gov/apod/image/2003/SaturnMoon_Sojuel_1824.jpg'
INFO: 2021-04-27 08:47:08,052: save_locally() 'Origin URL: http://apod.nasa.gov/apod/ap200316.html'
INFO: 2021-04-27 08:47:08,052: save_locally() 'Image URL: http://apod.nasa.gov/apod/image/2003/SaturnMoon_Sojuel_1824.jpg'
INFO: 2021-04-27 08:47:08,052: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/nasa_apod/SaturnMoon_Sojuel_1824.jpg'
INFO: 2021-04-27 08:47:20,716: save_locally() 'Download complete'
INFO: 2021-04-27 08:47:20,716: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:47:20,717: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:47:20,718: prepare_thread() 'Prepared buffer contains 98 images'
INFO: 2021-04-27 08:47:21,719: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:47:21,720: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:47:21,720: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:47:21,720: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:47:21,720: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:47:21,720: download_one() 'NASA Astro Pic of the Day: Queue size: 728'
INFO: 2021-04-27 08:47:21,720: download_one() 'NASA Astro Pic of the Day: Queue populated with 728 URLs'
INFO: 2021-04-27 08:47:21,720: download_queue_item() 'APOD URL: http://apod.nasa.gov/apod/ap201123.html'
INFO: 2021-04-27 08:47:22,718: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-04-27 08:47:25,613: download_queue_item() 'Image URL: http://apod.nasa.gov/apod/image/2011/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:47:25,613: save_locally() 'Origin URL: http://apod.nasa.gov/apod/ap201123.html'
INFO: 2021-04-27 08:47:25,613: save_locally() 'Image URL: http://apod.nasa.gov/apod/image/2011/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:47:25,613: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:47:33,753: save_locally() 'Download complete'
INFO: 2021-04-27 08:47:33,753: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:47:33,754: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:47:33,755: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg to unseen_downloads'
INFO: 2021-04-27 08:47:34,756: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:47:34,756: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:47:34,756: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:47:34,756: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:47:34,756: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:47:34,756: download_one() 'Flickr: Queue size: 80'
INFO: 2021-04-27 08:47:34,756: download_one() 'Flickr: Queue populated with 80 URLs'
INFO: 2021-04-27 08:47:34,756: save_locally() 'Origin URL: https://www.flickr.com/photos/93647178@N00/7527960260'
INFO: 2021-04-27 08:47:34,756: save_locally() 'Image URL: https://live.staticflickr.com/8284/7527960260_0597611c52_o.jpg'
INFO: 2021-04-27 08:47:34,756: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527960260_0597611c52_o.jpg'
INFO: 2021-04-27 08:47:38,451: save_locally() 'Download complete'
INFO: 2021-04-27 08:47:38,451: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:47:38,452: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:47:38,453: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527960260_0597611c52_o.jpg to unseen_downloads'
INFO: 2021-04-27 08:47:39,455: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:47:39,455: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:47:39,455: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:47:39,455: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:47:39,455: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:47:39,455: download_one() 'Earth View: Queue size: 1510'
INFO: 2021-04-27 08:47:39,455: download_one() 'Earth View: Queue populated with 1510 URLs'
INFO: 2021-04-27 08:47:39,455: save_locally() 'Origin URL: https://earthview.withgoogle.com/2157'
INFO: 2021-04-27 08:47:39,455: save_locally() 'Image URL: https://www.gstatic.com/prettyearth/assets/full/2157.jpg'
INFO: 2021-04-27 08:47:39,455: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Earth View/Kerman, Iran (ID-2157).jpg'
INFO: 2021-04-27 08:47:40,744: save_locally() 'Download complete'
INFO: 2021-04-27 08:47:40,744: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:47:40,745: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:47:40,746: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Earth View/Kerman, Iran (ID-2157).jpg to unseen_downloads'
INFO: 2021-04-27 08:47:41,747: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:47:41,747: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:47:41,747: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:47:41,747: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:47:41,747: download_one() 'Bing: Downloading an image, config: None'
INFO: 2021-04-27 08:47:41,747: download_one() 'Bing: Queue size: 5'
INFO: 2021-04-27 08:47:41,747: download_one() 'Bing: Queue populated with 5 URLs'
INFO: 2021-04-27 08:47:41,747: save_locally() 'Origin URL: https://www.bing.com/search?q=earth+day&form=hpcapt&filters=HpDate%3a%2220210422_0700%22'
INFO: 2021-04-27 08:47:41,747: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.MississippiRiver_EN-US2192534174_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2021-04-27 08:47:41,747: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Bing/OHR.MississippiRiver_EN-US2192534174_1920x1080.jpg'
INFO: 2021-04-27 08:47:42,855: save_locally() 'Download complete'
INFO: 2021-04-27 08:47:42,855: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:47:42,856: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:47:42,857: purge_downloaded() 'Refreshed download folder size: 5.8370819091796875 mb'
INFO: 2021-04-27 08:47:42,857: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Bing/OHR.MississippiRiver_EN-US2192534174_1920x1080.jpg to unseen_downloads'
INFO: 2021-04-27 08:47:43,859: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:47:43,859: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:47:43,859: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:47:43,859: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:47:43,859: download_one() 'Unsplash.com: Downloading an image, config: None'
INFO: 2021-04-27 08:47:43,859: download_one() 'Unsplash.com: Queue size: 0'
INFO: 2021-04-27 08:47:43,859: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:47:43,859: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:47:43,859: download_one() 'Unsplash.com: Queue empty, but max_queue_fills_per_hour of 1 reached, will try again later'
INFO: 2021-04-27 08:47:44,861: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:47:44,861: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:47:44,861: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:47:44,861: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:47:44,861: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:47:44,861: download_one() 'NASA Astro Pic of the Day: Queue size: 727'
INFO: 2021-04-27 08:47:44,861: download_one() 'NASA Astro Pic of the Day: Queue populated with 727 URLs'
INFO: 2021-04-27 08:47:44,861: download_queue_item() 'APOD URL: http://apod.nasa.gov/apod/ap191102.html'
INFO: 2021-04-27 08:47:47,321: download_queue_item() 'Image URL: http://apod.nasa.gov/apod/image/1405/Flamessc2014-04a_Med.jpg'
INFO: 2021-04-27 08:47:47,321: save_locally() 'Origin URL: http://apod.nasa.gov/apod/ap191102.html'
INFO: 2021-04-27 08:47:47,321: save_locally() 'Image URL: http://apod.nasa.gov/apod/image/1405/Flamessc2014-04a_Med.jpg'
INFO: 2021-04-27 08:47:47,321: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/nasa_apod/Flamessc2014-04a_Med.jpg'
INFO: 2021-04-27 08:47:50,404: save_locally() 'Download complete'
INFO: 2021-04-27 08:47:50,404: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:47:50,405: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:47:50,406: prepare_thread() 'Prepared buffer contains 98 images'
INFO: 2021-04-27 08:47:51,407: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:47:51,407: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:47:51,407: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:47:51,407: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:47:51,407: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:47:51,407: download_one() 'NASA Astro Pic of the Day: Queue size: 726'
INFO: 2021-04-27 08:47:51,407: download_one() 'NASA Astro Pic of the Day: Queue populated with 726 URLs'
INFO: 2021-04-27 08:47:51,407: download_queue_item() 'APOD URL: http://apod.nasa.gov/apod/ap210313.html'
INFO: 2021-04-27 08:47:52,407: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-04-27 08:47:53,823: download_queue_item() 'Image URL: http://apod.nasa.gov/apod/image/2103/pia24493-2-1041.jpg'
INFO: 2021-04-27 08:47:53,823: save_locally() 'Origin URL: http://apod.nasa.gov/apod/ap210313.html'
INFO: 2021-04-27 08:47:53,823: save_locally() 'Image URL: http://apod.nasa.gov/apod/image/2103/pia24493-2-1041.jpg'
INFO: 2021-04-27 08:47:53,823: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/nasa_apod/pia24493-2-1041.jpg'
INFO: 2021-04-27 08:47:57,622: save_locally() 'Download complete'
INFO: 2021-04-27 08:47:57,622: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:47:57,623: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:47:57,623: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/nasa_apod/pia24493-2-1041.jpg to unseen_downloads'
INFO: 2021-04-27 08:47:58,625: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:47:58,625: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:47:58,625: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:47:58,625: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:47:58,626: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:47:58,626: download_one() 'Flickr: Queue size: 79'
INFO: 2021-04-27 08:47:58,626: download_one() 'Flickr: Queue populated with 79 URLs'
INFO: 2021-04-27 08:47:58,626: save_locally() 'Origin URL: https://www.flickr.com/photos/93647178@N00/7527956106'
INFO: 2021-04-27 08:47:58,626: save_locally() 'Image URL: https://live.staticflickr.com/7137/7527956106_dedccb1439_o.jpg'
INFO: 2021-04-27 08:47:58,626: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527956106_dedccb1439_o.jpg'
INFO: 2021-04-27 08:48:00,355: save_locally() 'Download complete'
INFO: 2021-04-27 08:48:00,355: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:48:00,357: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:48:00,358: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527956106_dedccb1439_o.jpg to unseen_downloads'
INFO: 2021-04-27 08:48:01,360: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:48:01,360: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:48:01,360: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:48:01,360: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:48:01,360: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:48:01,360: download_one() 'Earth View: Queue size: 1509'
INFO: 2021-04-27 08:48:01,360: download_one() 'Earth View: Queue populated with 1509 URLs'
INFO: 2021-04-27 08:48:01,361: save_locally() 'Origin URL: https://earthview.withgoogle.com/6184'
INFO: 2021-04-27 08:48:01,361: save_locally() 'Image URL: https://www.gstatic.com/prettyearth/assets/full/6184.jpg'
INFO: 2021-04-27 08:48:01,361: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Earth View/Mili Atoll, Marshall Islands (ID-6184).jpg'
INFO: 2021-04-27 08:48:02,496: save_locally() 'Download complete'
INFO: 2021-04-27 08:48:02,496: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:48:02,497: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:48:02,497: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Earth View/Mili Atoll, Marshall Islands (ID-6184).jpg to unseen_downloads'
INFO: 2021-04-27 08:48:03,499: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:48:03,499: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:48:03,499: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:48:03,499: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:48:03,499: download_one() 'Bing: Downloading an image, config: None'
INFO: 2021-04-27 08:48:03,499: download_one() 'Bing: Queue size: 4'
INFO: 2021-04-27 08:48:03,499: download_one() 'Bing: Queue populated with 4 URLs'
INFO: 2021-04-27 08:48:03,499: save_locally() 'Origin URL: https://www.bing.com/search?q=Mobula+munkiana&form=hpcapt&filters=HpDate%3a%2220210419_0700%22'
INFO: 2021-04-27 08:48:03,499: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.Mobula_EN-US7757384682_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2021-04-27 08:48:03,499: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Bing/OHR.Mobula_EN-US7757384682_1920x1080.jpg'
INFO: 2021-04-27 08:48:04,982: save_locally() 'Download complete'
INFO: 2021-04-27 08:48:04,982: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:48:04,983: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:48:04,984: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Bing/OHR.Mobula_EN-US7757384682_1920x1080.jpg to unseen_downloads'
INFO: 2021-04-27 08:48:05,985: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:48:05,985: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:48:05,986: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:48:05,986: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:48:05,986: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:48:05,986: download_one() 'NASA Astro Pic of the Day: Queue size: 725'
INFO: 2021-04-27 08:48:05,986: download_one() 'NASA Astro Pic of the Day: Queue populated with 725 URLs'
INFO: 2021-04-27 08:48:05,986: download_queue_item() 'APOD URL: http://apod.nasa.gov/apod/ap190504.html'
INFO: 2021-04-27 08:48:10,009: download_queue_item() 'Image URL: http://apod.nasa.gov/apod/image/1905/20190202tezel.jpg'
INFO: 2021-04-27 08:48:10,009: save_locally() 'Origin URL: http://apod.nasa.gov/apod/ap190504.html'
INFO: 2021-04-27 08:48:10,009: save_locally() 'Image URL: http://apod.nasa.gov/apod/image/1905/20190202tezel.jpg'
INFO: 2021-04-27 08:48:10,009: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/nasa_apod/20190202tezel.jpg'
INFO: 2021-04-27 08:48:22,435: save_locally() 'Download complete'
INFO: 2021-04-27 08:48:22,435: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:48:22,436: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:48:22,436: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/nasa_apod/20190202tezel.jpg to unseen_downloads'
INFO: 2021-04-27 08:48:23,437: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:48:23,437: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:48:23,437: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:48:23,437: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:48:23,437: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:48:23,437: download_one() 'Flickr: Queue size: 78'
INFO: 2021-04-27 08:48:23,437: download_one() 'Flickr: Queue populated with 78 URLs'
INFO: 2021-04-27 08:48:23,437: save_locally() 'Origin URL: https://www.flickr.com/photos/93647178@N00/7527890586'
INFO: 2021-04-27 08:48:23,437: save_locally() 'Image URL: https://live.staticflickr.com/7110/7527890586_0f8be39bde_o.jpg'
INFO: 2021-04-27 08:48:23,437: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527890586_0f8be39bde_o.jpg'
INFO: 2021-04-27 08:48:25,562: save_locally() 'Download complete'
INFO: 2021-04-27 08:48:25,563: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:48:25,565: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:48:25,567: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527890586_0f8be39bde_o.jpg to unseen_downloads'
INFO: 2021-04-27 08:48:26,568: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:48:26,568: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:48:26,568: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:48:26,568: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:48:26,568: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:48:26,568: download_one() 'Earth View: Queue size: 1508'
INFO: 2021-04-27 08:48:26,568: download_one() 'Earth View: Queue populated with 1508 URLs'
INFO: 2021-04-27 08:48:26,568: save_locally() 'Origin URL: https://earthview.withgoogle.com/1589'
INFO: 2021-04-27 08:48:26,568: save_locally() 'Image URL: https://www.gstatic.com/prettyearth/assets/full/1589.jpg'
INFO: 2021-04-27 08:48:26,568: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Earth View/Redwood City, United States (ID-1589).jpg'
INFO: 2021-04-27 08:48:27,985: save_locally() 'Download complete'
INFO: 2021-04-27 08:48:27,986: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:48:27,986: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:48:27,987: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Earth View/Redwood City, United States (ID-1589).jpg to unseen_downloads'
INFO: 2021-04-27 08:48:28,988: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:48:28,988: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:48:28,988: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:48:28,988: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:48:28,988: download_one() 'Bing: Downloading an image, config: None'
INFO: 2021-04-27 08:48:28,988: download_one() 'Bing: Queue size: 3'
INFO: 2021-04-27 08:48:28,988: download_one() 'Bing: Queue populated with 3 URLs'
INFO: 2021-04-27 08:48:28,989: save_locally() 'Origin URL: https://www.bing.com/search?q=wensleydale+england&form=hpcapt&filters=HpDate%3a%2220210426_0700%22'
INFO: 2021-04-27 08:48:28,989: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.Wensleydale_EN-US0930314934_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2021-04-27 08:48:28,989: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Bing/OHR.Wensleydale_EN-US0930314934_1920x1080.jpg'
INFO: 2021-04-27 08:48:29,948: save_locally() 'Download complete'
INFO: 2021-04-27 08:48:29,948: update_indicator() 'Setting file info to: /usr/share/wallpapers/garuda-wallpapers/garuda-wp-BSPWM-03.png'
INFO: 2021-04-27 08:48:29,949: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:48:29,949: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Bing/OHR.Wensleydale_EN-US0930314934_1920x1080.jpg to unseen_downloads'
INFO: 2021-04-27 08:48:30,951: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:48:30,951: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:48:30,951: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:48:30,951: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:48:30,951: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:48:30,951: download_one() 'NASA Astro Pic of the Day: Queue size: 724'
INFO: 2021-04-27 08:48:30,951: download_one() 'NASA Astro Pic of the Day: Queue populated with 724 URLs'
INFO: 2021-04-27 08:48:30,952: download_queue_item() 'APOD URL: http://apod.nasa.gov/apod/ap190730.html'
INFO: 2021-04-27 08:48:32,785: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2021-04-27 08:48:32,785: set_wallpaper() 'Calling set_wallpaper with /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:48:32,785: prepare_thread() 'Prepared buffer contains 98 images'
INFO: 2021-04-27 08:48:32,786: do_set_wp() 'Calling do_set_wp with /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg, time: 1619493512.7863595'
INFO: 2021-04-27 08:48:32,797: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:48:32,798: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:48:33,484: download_queue_item() 'Image URL: http://apod.nasa.gov/apod/image/1907/ngc3576_campbell_1824.jpg'
INFO: 2021-04-27 08:48:33,484: save_locally() 'Origin URL: http://apod.nasa.gov/apod/ap190730.html'
INFO: 2021-04-27 08:48:33,484: save_locally() 'Image URL: http://apod.nasa.gov/apod/image/1907/ngc3576_campbell_1824.jpg'
INFO: 2021-04-27 08:48:33,484: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/nasa_apod/ngc3576_campbell_1824.jpg'
INFO: 2021-04-27 08:48:34,786: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-04-27 08:48:34,786: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-04-27 08:48:45,713: save_locally() 'Download complete'
INFO: 2021-04-27 08:48:45,713: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:48:45,713: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:48:45,714: prepare_thread() 'Prepared buffer contains 98 images'
INFO: 2021-04-27 08:48:46,716: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:48:46,716: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:48:46,716: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:48:46,716: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:48:46,716: download_one() 'Unsplash.com: Downloading an image, config: None'
INFO: 2021-04-27 08:48:46,717: download_one() 'Unsplash.com: Queue size: 0'
INFO: 2021-04-27 08:48:46,717: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:48:46,717: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:48:46,717: download_one() 'Unsplash.com: Queue empty, but max_queue_fills_per_hour of 1 reached, will try again later'
INFO: 2021-04-27 08:48:47,715: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-04-27 08:48:47,718: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:48:47,718: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:48:47,718: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:48:47,718: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:48:47,718: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:48:47,718: download_one() 'NASA Astro Pic of the Day: Queue size: 723'
INFO: 2021-04-27 08:48:47,718: download_one() 'NASA Astro Pic of the Day: Queue populated with 723 URLs'
INFO: 2021-04-27 08:48:47,718: download_queue_item() 'APOD URL: http://apod.nasa.gov/apod/ap200523.html'
INFO: 2021-04-27 08:48:51,548: download_queue_item() 'Image URL: http://apod.nasa.gov/apod/image/2005/IMG_1478-Edit.jpg'
INFO: 2021-04-27 08:48:51,549: save_locally() 'Origin URL: http://apod.nasa.gov/apod/ap200523.html'
INFO: 2021-04-27 08:48:51,549: save_locally() 'Image URL: http://apod.nasa.gov/apod/image/2005/IMG_1478-Edit.jpg'
INFO: 2021-04-27 08:48:51,549: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/nasa_apod/IMG_1478-Edit.jpg'
INFO: 2021-04-27 08:49:12,341: save_locally() 'Download complete'
INFO: 2021-04-27 08:49:12,341: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:49:12,342: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:49:12,343: prepare_thread() 'Prepared buffer contains 98 images'
INFO: 2021-04-27 08:49:13,345: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:49:13,345: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:49:13,345: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:49:13,345: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:49:13,346: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:49:13,346: download_one() 'NASA Astro Pic of the Day: Queue size: 722'
INFO: 2021-04-27 08:49:13,346: download_one() 'NASA Astro Pic of the Day: Queue populated with 722 URLs'
INFO: 2021-04-27 08:49:13,346: download_queue_item() 'APOD URL: http://apod.nasa.gov/apod/ap200411.html'
INFO: 2021-04-27 08:49:14,344: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-04-27 08:49:17,547: download_queue_item() 'Image URL: http://apod.nasa.gov/apod/image/2004/TimelapseVenusPleiadesFinazzi.jpg'
INFO: 2021-04-27 08:49:17,547: save_locally() 'Origin URL: http://apod.nasa.gov/apod/ap200411.html'
INFO: 2021-04-27 08:49:17,547: save_locally() 'Image URL: http://apod.nasa.gov/apod/image/2004/TimelapseVenusPleiadesFinazzi.jpg'
INFO: 2021-04-27 08:49:17,547: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/nasa_apod/TimelapseVenusPleiadesFinazzi.jpg'
INFO: 2021-04-27 08:49:27,787: save_locally() 'Download complete'
INFO: 2021-04-27 08:49:27,787: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:49:27,788: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:49:27,788: prepare_thread() 'Prepared buffer contains 98 images'
INFO: 2021-04-27 08:49:28,790: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:49:28,790: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:49:28,790: get_throttling() 'NASA Astro Pic of the Day: parsing serverside options'
INFO: 2021-04-27 08:49:28,790: get_throttling() 'Could not parse NASA Astro Pic of the Day serverside options, using defaults None, None'
INFO: 2021-04-27 08:49:28,790: download_one() 'NASA Astro Pic of the Day: Downloading an image, config: None'
INFO: 2021-04-27 08:49:28,790: download_one() 'NASA Astro Pic of the Day: Queue size: 721'
INFO: 2021-04-27 08:49:28,790: download_one() 'NASA Astro Pic of the Day: Queue populated with 721 URLs'
INFO: 2021-04-27 08:49:28,790: download_queue_item() 'APOD URL: http://apod.nasa.gov/apod/ap190825.html'
INFO: 2021-04-27 08:49:29,789: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-04-27 08:49:32,182: download_queue_item() 'No image url found for this APOD URL'
INFO: 2021-04-27 08:49:33,184: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:49:33,184: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:49:33,184: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:49:33,184: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:49:33,184: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:49:33,184: download_one() 'Flickr: Queue size: 77'
INFO: 2021-04-27 08:49:33,184: download_one() 'Flickr: Queue populated with 77 URLs'
INFO: 2021-04-27 08:49:33,184: save_locally() 'Origin URL: https://www.flickr.com/photos/93647178@N00/7527959832'
INFO: 2021-04-27 08:49:33,184: save_locally() 'Image URL: https://live.staticflickr.com/7267/7527959832_fbb4d21ff9_o.jpg'
INFO: 2021-04-27 08:49:33,184: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527959832_fbb4d21ff9_o.jpg'
INFO: 2021-04-27 08:49:35,161: save_locally() 'Download complete'
INFO: 2021-04-27 08:49:35,161: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:49:35,162: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:49:35,162: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527959832_fbb4d21ff9_o.jpg to unseen_downloads'
INFO: 2021-04-27 08:49:36,164: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:49:36,164: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:49:36,164: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:49:36,164: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:49:36,164: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:49:36,164: download_one() 'Earth View: Queue size: 1507'
INFO: 2021-04-27 08:49:36,164: download_one() 'Earth View: Queue populated with 1507 URLs'
INFO: 2021-04-27 08:49:36,164: save_locally() 'Origin URL: https://earthview.withgoogle.com/5646'
INFO: 2021-04-27 08:49:36,164: save_locally() 'Image URL: https://www.gstatic.com/prettyearth/assets/full/5646.jpg'
INFO: 2021-04-27 08:49:36,164: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Earth View/Hamburg, Germany (ID-5646).jpg'
INFO: 2021-04-27 08:49:37,621: save_locally() 'Download complete'
INFO: 2021-04-27 08:49:37,621: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:49:37,622: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:49:37,622: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Earth View/Hamburg, Germany (ID-5646).jpg to unseen_downloads'
INFO: 2021-04-27 08:49:38,625: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:49:38,625: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:49:38,625: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:49:38,625: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:49:38,625: download_one() 'Bing: Downloading an image, config: None'
INFO: 2021-04-27 08:49:38,625: download_one() 'Bing: Queue size: 2'
INFO: 2021-04-27 08:49:38,625: download_one() 'Bing: Queue populated with 2 URLs'
INFO: 2021-04-27 08:49:38,625: save_locally() 'Origin URL: https://www.bing.com/search?q=ad%C3%A9lie+penguin&form=hpcapt&filters=HpDate%3a%2220210425_0700%22'
INFO: 2021-04-27 08:49:38,625: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.AdelieDiving_EN-US0845944074_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2021-04-27 08:49:38,625: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Bing/OHR.AdelieDiving_EN-US0845944074_1920x1080.jpg'
INFO: 2021-04-27 08:49:39,878: save_locally() 'Download complete'
INFO: 2021-04-27 08:49:39,878: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:49:39,878: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:49:39,879: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Bing/OHR.AdelieDiving_EN-US0845944074_1920x1080.jpg to unseen_downloads'
INFO: 2021-04-27 08:49:40,881: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:49:40,881: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:49:40,881: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:49:40,881: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:49:40,881: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:49:40,881: download_one() 'Flickr: Queue size: 76'
INFO: 2021-04-27 08:49:40,881: download_one() 'Flickr: Queue populated with 76 URLs'
INFO: 2021-04-27 08:49:40,881: save_locally() 'Origin URL: https://www.flickr.com/photos/93647178@N00/7527878436'
INFO: 2021-04-27 08:49:40,881: save_locally() 'Image URL: https://live.staticflickr.com/7110/7527878436_fdd7b3909b_o.jpg'
INFO: 2021-04-27 08:49:40,881: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527878436_fdd7b3909b_o.jpg'
INFO: 2021-04-27 08:49:42,959: save_locally() 'Download complete'
INFO: 2021-04-27 08:49:42,960: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:49:42,960: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:49:42,961: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527878436_fdd7b3909b_o.jpg to unseen_downloads'
INFO: 2021-04-27 08:49:43,962: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:49:43,962: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:49:43,962: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:49:43,962: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:49:43,962: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:49:43,962: download_one() 'Earth View: Queue size: 1506'
INFO: 2021-04-27 08:49:43,962: download_one() 'Earth View: Queue populated with 1506 URLs'
INFO: 2021-04-27 08:49:43,962: save_locally() 'Origin URL: https://earthview.withgoogle.com/1464'
INFO: 2021-04-27 08:49:43,962: save_locally() 'Image URL: https://www.gstatic.com/prettyearth/assets/full/1464.jpg'
INFO: 2021-04-27 08:49:43,962: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Earth View/Frankfurt, Germany (ID-1464).jpg'
INFO: 2021-04-27 08:49:45,368: save_locally() 'Download complete'
INFO: 2021-04-27 08:49:45,368: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:49:45,369: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:49:45,369: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Earth View/Frankfurt, Germany (ID-1464).jpg to unseen_downloads'
INFO: 2021-04-27 08:49:46,371: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:49:46,371: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:49:46,371: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:49:46,371: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:49:46,371: download_one() 'Bing: Downloading an image, config: None'
INFO: 2021-04-27 08:49:46,371: download_one() 'Bing: Queue size: 1'
INFO: 2021-04-27 08:49:46,371: download_one() 'Bing: Queue populated with 1 URLs'
INFO: 2021-04-27 08:49:46,371: save_locally() 'Origin URL: https://www.bing.com/search?q=%2btegallalang+rice+terrace&FORM=hpcapt&filters=HpDate%3a%2220210420_0700%22'
INFO: 2021-04-27 08:49:46,371: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.Ceking_EN-US7899895685_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2021-04-27 08:49:46,371: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Bing/OHR.Ceking_EN-US7899895685_1920x1080.jpg'
INFO: 2021-04-27 08:49:47,864: save_locally() 'Download complete'
INFO: 2021-04-27 08:49:47,864: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:49:47,865: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:49:47,865: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Bing/OHR.Ceking_EN-US7899895685_1920x1080.jpg to unseen_downloads'
INFO: 2021-04-27 08:49:48,867: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:49:48,867: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:49:48,867: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:49:48,867: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:49:48,867: download_one() 'Unsplash.com: Downloading an image, config: None'
INFO: 2021-04-27 08:49:48,867: download_one() 'Unsplash.com: Queue size: 0'
INFO: 2021-04-27 08:49:48,867: get_throttling() 'Unsplash.com: parsing serverside options'
INFO: 2021-04-27 08:49:48,867: get_throttling() 'Could not parse Unsplash.com serverside options, using defaults 10, 1'
INFO: 2021-04-27 08:49:48,867: download_one() 'Unsplash.com: Queue empty, but max_queue_fills_per_hour of 1 reached, will try again later'
INFO: 2021-04-27 08:49:49,869: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:49:49,869: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:49:49,869: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:49:49,869: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:49:49,869: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:49:49,869: download_one() 'Flickr: Queue size: 75'
INFO: 2021-04-27 08:49:49,869: download_one() 'Flickr: Queue populated with 75 URLs'
INFO: 2021-04-27 08:49:49,869: save_locally() 'Origin URL: https://www.flickr.com/photos/93647178@N00/7527921052'
INFO: 2021-04-27 08:49:49,870: save_locally() 'Image URL: https://live.staticflickr.com/8145/7527921052_6a697ef126_o.jpg'
INFO: 2021-04-27 08:49:49,870: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527921052_6a697ef126_o.jpg'
INFO: 2021-04-27 08:49:51,915: save_locally() 'Download complete'
INFO: 2021-04-27 08:49:51,915: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:49:51,916: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:49:51,917: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527921052_6a697ef126_o.jpg to unseen_downloads'
INFO: 2021-04-27 08:49:52,919: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:49:52,919: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:49:52,919: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:49:52,919: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:49:52,919: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:49:52,919: download_one() 'Earth View: Queue size: 1505'
INFO: 2021-04-27 08:49:52,919: download_one() 'Earth View: Queue populated with 1505 URLs'
INFO: 2021-04-27 08:49:52,920: save_locally() 'Origin URL: https://earthview.withgoogle.com/1567'
INFO: 2021-04-27 08:49:52,920: save_locally() 'Image URL: https://www.gstatic.com/prettyearth/assets/full/1567.jpg'
INFO: 2021-04-27 08:49:52,920: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Earth View/Al Jowf, Saudi Arabia (ID-1567).jpg'
INFO: 2021-04-27 08:49:54,040: save_locally() 'Download complete'
INFO: 2021-04-27 08:49:54,040: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:49:54,040: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:49:54,041: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Earth View/Al Jowf, Saudi Arabia (ID-1567).jpg to unseen_downloads'
INFO: 2021-04-27 08:49:55,042: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:49:55,042: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:49:55,042: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:49:55,042: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:49:55,042: download_one() 'Bing: Downloading an image, config: None'
INFO: 2021-04-27 08:49:55,042: download_one() 'Bing: Queue size: 0'
INFO: 2021-04-27 08:49:55,042: get_throttling() 'Bing: parsing serverside options'
INFO: 2021-04-27 08:49:55,042: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2021-04-27 08:49:55,042: download_one() 'Bing: Filling queue'
INFO: 2021-04-27 08:49:55,620: download_one() 'Bing: Queue populated with 7 URLs'
INFO: 2021-04-27 08:49:55,620: save_locally() 'Origin URL: https://www.bing.com/search?q=Mobula+munkiana&form=hpcapt&filters=HpDate%3a%2220210419_0700%22'
INFO: 2021-04-27 08:49:55,620: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.Mobula_EN-US7757384682_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2021-04-27 08:49:55,620: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Bing/OHR.Mobula_EN-US7757384682_1920x1080.jpg'
INFO: 2021-04-27 08:49:55,620: save_locally() 'File already exists, skip downloading'
INFO: 2021-04-27 08:49:56,622: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:49:56,622: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:49:56,622: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:49:56,622: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:49:56,622: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:49:56,622: download_one() 'Flickr: Queue size: 74'
INFO: 2021-04-27 08:49:56,622: download_one() 'Flickr: Queue populated with 74 URLs'
INFO: 2021-04-27 08:49:56,622: save_locally() 'Origin URL: https://www.flickr.com/photos/93647178@N00/7527889552'
INFO: 2021-04-27 08:49:56,622: save_locally() 'Image URL: https://live.staticflickr.com/7114/7527889552_795071a136_o.jpg'
INFO: 2021-04-27 08:49:56,622: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527889552_795071a136_o.jpg'
INFO: 2021-04-27 08:49:58,367: save_locally() 'Download complete'
INFO: 2021-04-27 08:49:58,367: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:49:58,368: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:49:58,368: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527889552_795071a136_o.jpg to unseen_downloads'
INFO: 2021-04-27 08:49:59,369: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:49:59,369: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:49:59,369: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:49:59,369: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:49:59,369: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:49:59,369: download_one() 'Earth View: Queue size: 1504'
INFO: 2021-04-27 08:49:59,369: download_one() 'Earth View: Queue populated with 1504 URLs'
INFO: 2021-04-27 08:49:59,369: save_locally() 'Origin URL: https://earthview.withgoogle.com/1265'
INFO: 2021-04-27 08:49:59,369: save_locally() 'Image URL: https://www.gstatic.com/prettyearth/assets/full/1265.jpg'
INFO: 2021-04-27 08:49:59,369: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Earth View/Austin, United States (ID-1265).jpg'
INFO: 2021-04-27 08:50:00,782: save_locally() 'Download complete'
INFO: 2021-04-27 08:50:00,782: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:50:00,783: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:50:00,783: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Earth View/Austin, United States (ID-1265).jpg to unseen_downloads'
INFO: 2021-04-27 08:50:01,786: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:50:01,786: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:50:01,786: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:50:01,786: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:50:01,786: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:50:01,786: download_one() 'Flickr: Queue size: 73'
INFO: 2021-04-27 08:50:01,786: download_one() 'Flickr: Queue populated with 73 URLs'
INFO: 2021-04-27 08:50:01,786: save_locally() 'Origin URL: https://www.flickr.com/photos/93647178@N00/7527944686'
INFO: 2021-04-27 08:50:01,786: save_locally() 'Image URL: https://live.staticflickr.com/8024/7527944686_de592c2745_o.jpg'
INFO: 2021-04-27 08:50:01,786: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527944686_de592c2745_o.jpg'
INFO: 2021-04-27 08:50:03,467: save_locally() 'Download complete'
INFO: 2021-04-27 08:50:03,467: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:50:03,467: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:50:03,468: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527944686_de592c2745_o.jpg to unseen_downloads'
INFO: 2021-04-27 08:50:04,471: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:50:04,471: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:50:04,471: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:50:04,471: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:50:04,471: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:50:04,471: download_one() 'Earth View: Queue size: 1503'
INFO: 2021-04-27 08:50:04,471: download_one() 'Earth View: Queue populated with 1503 URLs'
INFO: 2021-04-27 08:50:04,472: save_locally() 'Origin URL: https://earthview.withgoogle.com/1215'
INFO: 2021-04-27 08:50:04,472: save_locally() 'Image URL: https://www.gstatic.com/prettyearth/assets/full/1215.jpg'
INFO: 2021-04-27 08:50:04,472: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Earth View/Baiyin, China (ID-1215).jpg'
INFO: 2021-04-27 08:50:06,057: save_locally() 'Download complete'
INFO: 2021-04-27 08:50:06,057: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:50:06,058: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:50:06,059: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Earth View/Baiyin, China (ID-1215).jpg to unseen_downloads'
INFO: 2021-04-27 08:50:07,062: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:50:07,062: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:50:07,062: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:50:07,062: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:50:07,062: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:50:07,062: download_one() 'Flickr: Queue size: 72'
INFO: 2021-04-27 08:50:07,062: download_one() 'Flickr: Queue populated with 72 URLs'
INFO: 2021-04-27 08:50:07,062: save_locally() 'Origin URL: https://www.flickr.com/photos/93647178@N00/7527796044'
INFO: 2021-04-27 08:50:07,062: save_locally() 'Image URL: https://live.staticflickr.com/8430/7527796044_10be1ff750_o.jpg'
INFO: 2021-04-27 08:50:07,062: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527796044_10be1ff750_o.jpg'
INFO: 2021-04-27 08:50:09,165: save_locally() 'Download complete'
INFO: 2021-04-27 08:50:09,165: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:50:09,166: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:50:09,167: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527796044_10be1ff750_o.jpg to unseen_downloads'
INFO: 2021-04-27 08:50:10,169: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:50:10,169: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:50:10,169: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:50:10,169: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:50:10,169: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:50:10,170: download_one() 'Earth View: Queue size: 1502'
INFO: 2021-04-27 08:50:10,170: download_one() 'Earth View: Queue populated with 1502 URLs'
INFO: 2021-04-27 08:50:10,170: save_locally() 'Origin URL: https://earthview.withgoogle.com/5484'
INFO: 2021-04-27 08:50:10,170: save_locally() 'Image URL: https://www.gstatic.com/prettyearth/assets/full/5484.jpg'
INFO: 2021-04-27 08:50:10,170: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Earth View/Polańczyk, Poland (ID-5484).jpg'
INFO: 2021-04-27 08:50:12,465: save_locally() 'Download complete'
INFO: 2021-04-27 08:50:12,465: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:50:12,466: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:50:12,466: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Earth View/Polańczyk, Poland (ID-5484).jpg to unseen_downloads'
INFO: 2021-04-27 08:50:13,468: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:50:13,468: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:50:13,468: get_throttling() 'Flickr: parsing serverside options'
INFO: 2021-04-27 08:50:13,468: get_throttling() 'Could not parse Flickr serverside options, using defaults 120, 20'
INFO: 2021-04-27 08:50:13,468: download_one() 'Flickr: Downloading an image, config: user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2021-04-27 08:50:13,468: download_one() 'Flickr: Queue size: 71'
INFO: 2021-04-27 08:50:13,468: download_one() 'Flickr: Queue populated with 71 URLs'
INFO: 2021-04-27 08:50:13,468: save_locally() 'Origin URL: https://www.flickr.com/photos/93647178@N00/7527875128'
INFO: 2021-04-27 08:50:13,468: save_locally() 'Image URL: https://live.staticflickr.com/8154/7527875128_0651ec7427_o.jpg'
INFO: 2021-04-27 08:50:13,468: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527875128_0651ec7427_o.jpg'
INFO: 2021-04-27 08:50:15,496: save_locally() 'Download complete'
INFO: 2021-04-27 08:50:15,496: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:50:15,496: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:50:15,497: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527875128_0651ec7427_o.jpg to unseen_downloads'
INFO: 2021-04-27 08:50:16,499: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:50:16,500: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:50:16,500: get_throttling() 'Earth View: parsing serverside options'
INFO: 2021-04-27 08:50:16,500: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2021-04-27 08:50:16,500: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2021-04-27 08:50:16,500: download_one() 'Earth View: Queue size: 1501'
INFO: 2021-04-27 08:50:16,500: download_one() 'Earth View: Queue populated with 1501 URLs'
INFO: 2021-04-27 08:50:16,500: save_locally() 'Origin URL: https://earthview.withgoogle.com/1694'
INFO: 2021-04-27 08:50:16,500: save_locally() 'Image URL: https://www.gstatic.com/prettyearth/assets/full/1694.jpg'
INFO: 2021-04-27 08:50:16,500: save_locally() 'Local path: /home/shivakantm/.config/variety/Downloaded/Earth View/Washington, United States (ID-1694).jpg'
INFO: 2021-04-27 08:50:17,652: save_locally() 'Download complete'
INFO: 2021-04-27 08:50:17,652: update_indicator() 'Setting file info to: /home/shivakantm/.config/variety/Downloaded/nasa_apod/JupiterVista_JunoGill_3688.jpg'
INFO: 2021-04-27 08:50:17,653: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-04-27 08:50:17,653: download_one_from() 'Adding downloaded file /home/shivakantm/.config/variety/Downloaded/Earth View/Washington, United States (ID-1694).jpg to unseen_downloads'
